- name: Set CPU arch mapping fact
  ansible.builtin.set_fact:
    aws_sam_cli__cpu_arch_mapping:
      x86_64: x86_64
      aarch64: arm64

- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Set packages to install fact
  when: aws_sam_cli__packages is not defined
  ansible.builtin.set_fact:
    aws_sam_cli__packages: "{{ _aws_sam_cli__packages | list }}"

- name: Install dependencies
  ansible.builtin.package:
    name: "{{ aws_sam_cli__packages }}"
    state: present
  become: true

- name: Get installed version
  ansible.builtin.shell:
    executable: /usr/bin/bash
    cmd: |
      set -euo pipefail
      export PATH=/usr/local/bin:$PATH
      if command -v sam &> /dev/null; then
        sam --version | sed -n -E 's/.*version (.+)/\1/p'
      fi
  register: aws_sam_cli__get_installed_version
  changed_when: false

- name: Set installed version fact
  ansible.builtin.set_fact:
    aws_sam_cli__installed_version: >-
      {{ aws_sam_cli__get_installed_version.stdout | regex_search(".+\..+\..+") }}

- name: Print installed version fact
  ansible.builtin.debug:
    var: aws_sam_cli__installed_version

- name: Set empty archive URL fact
  ansible.builtin.set_fact:
    aws_sam_cli__archive_url: ""

- name: Set archive URL fact for target exact
  when: >-
    aws_sam_cli__version not in ["present", "latest"]
    and aws_sam_cli__installed_version != aws_sam_cli__version
  ansible.builtin.set_fact:
    aws_sam_cli__archive_url: "{{ parts | join }}"
  vars:
    parts:
      - https://github.com/aws/aws-sam-cli/releases/download/v
      - "{{ aws_sam_cli__version }}"
      - /aws-sam-cli-linux-
      - "{{ aws_sam_cli__cpu_arch_mapping[ansible_architecture] }}"
      - .zip

- name: Set archive URL fact for target present
  when: aws_sam_cli__version == "present" and aws_sam_cli__installed_version == ""
  ansible.builtin.set_fact:
    aws_sam_cli__archive_url: "{{ parts | join }}"
  vars:
    parts:
      - https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-
      - "{{ aws_sam_cli__cpu_arch_mapping[ansible_architecture] }}"
      - .zip

- name: Determine archive URL fact for target latest
  when: aws_sam_cli__version == "latest"
  block:
    - name: Get latest version
      ansible.builtin.shell:
        executable: /usr/bin/bash
        cmd: |
          set -euo pipefail
          curl --silent --fail-with-body {{ changelog_url }} \
            | sed -n -E 's/.*"tag_name": "(.+)",.*/\1/p' \
            | cut -c2-
      vars:
        changelog_url: https://api.github.com/repos/aws/aws-sam-cli/releases/latest
      changed_when: false
      register: aws_sam_cli__get_latest_version

    - name: Set latest version fact
      ansible.builtin.set_fact:
        aws_sam_cli__latest_version: >-
          {{ aws_sam_cli__get_latest_version.stdout | regex_search(".+\..+\..+") }}

    - name: Print latest version fact
      ansible.builtin.debug:
        var: aws_sam_cli__latest_version

    - name: Set archive URL fact for target latest
      when: aws_sam_cli__installed_version != aws_sam_cli__latest_version
      ansible.builtin.set_fact:
        aws_sam_cli__archive_url: "{{ parts | join }}"
      vars:
        parts:
          - https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-
          - "{{ aws_sam_cli__cpu_arch_mapping[ansible_architecture] }}"
          - .zip

- name: Print archive URL fact
  ansible.builtin.debug:
    var: aws_sam_cli__archive_url

- name: Install
  when: aws_sam_cli__archive_url != ""
  become: true
  block:
    - name: Uninstall
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
        force: true
      loop:
        - "{{ aws_sam_cli__bin_dir }}/sam"
        - "{{ aws_sam_cli__install_dir }}"

    - name: Create tmp dir
      ansible.builtin.tempfile:
        state: directory
      register: aws_sam_cli__tmp_dir

    - name: Download archive
      ansible.builtin.get_url:
        url: "{{ aws_sam_cli__archive_url }}"
        dest: "{{ aws_sam_cli__tmp_dir.path }}/aws-sam-cli.zip"
        force: true
        mode: u=rw,g=,o=
      register: aws_sam_cli__download_archive

    - name: Download signature
      ansible.builtin.get_url:
        url: "{{ aws_sam_cli__archive_url }}.sig"
        dest: "{{ aws_sam_cli__tmp_dir.path }}/aws-sam-cli.zip.sig"
        force: true
        mode: u=rw,g=,o=
      register: aws_sam_cli_download_signature

    - name: Place public key
      ansible.builtin.copy:
        src: aws-sam-cli-public-key.asc
        dest: "{{ aws_sam_cli__tmp_dir.path }}"
        mode: u=rw,g=,o=
      register: aws_sam_cli__place_public_key

    - name: Verify integrity
      ansible.builtin.shell:
        executable: /usr/bin/bash
        cmd: |
          set -euo pipefail

          export GNUPGHOME={{ aws_sam_cli__tmp_dir.path }}/gnupg
          mkdir -m 0700 $GNUPGHOME

          gpg --yes --import {{ aws_sam_cli__place_public_key.dest }}

          gpg --verify \
            {{ aws_sam_cli_download_signature.dest }} \
            {{ aws_sam_cli__download_archive.dest }}
      changed_when: false

    - name: Unzip archive
      ansible.builtin.unarchive:
        src: "{{ aws_sam_cli__download_archive.dest }}"
        dest: "{{ aws_sam_cli__tmp_dir.path }}"
        remote_src: true
      register: aws_sam_cli__unzip_archive

    - name: Install
      ansible.builtin.command: >-
        {{ aws_sam_cli__unzip_archive.dest }}/install
        --bin-dir {{ aws_sam_cli__bin_dir }}
        --install-dir {{ aws_sam_cli__install_dir }}
      changed_when: true

    - name: Test executable
      ansible.builtin.command:
        cmd: >-
          {{ aws_sam_cli__bin_dir }}/sam --version
      changed_when: false
