- name: Verify 2 Latest
  hosts: all

  tasks:
    - name: Get installed version
      ansible.builtin.shell:
        executable: /usr/bin/bash
        cmd: |
          set -euo pipefail
          export PATH=/usr/local/bin:$PATH
          if command -v sam &> /dev/null; then
            sam --version | sed -n -E 's/.*version (.+)/\1/p'
          fi
      changed_when: false
      register: get_installed_version

    - name: Set installed version fact
      ansible.builtin.set_fact:
        installed_version: >-
          {{ get_installed_version.stdout | regex_search(".+\..+\..+") }}

    - name: Get latest version
      ansible.builtin.shell:
        executable: /usr/bin/bash
        cmd: |
          set -euo pipefail
          curl --silent --fail-with-body {{ release_url }} \
            | sed -n -E 's/.*"tag_name": "(.+)",.*/\1/p' \
            | cut -c2-
      vars:
        release_url: https://api.github.com/repos/aws/aws-sam-cli/releases/latest
      changed_when: false
      register: get_latest_version

    - name: Set latest version fact
      ansible.builtin.set_fact:
        latest_version: >-
          {{ get_latest_version.stdout | regex_search(".+\..+\..+") }}

    - name: Assert installed version correct
      ansible.builtin.assert:
        that:
          - installed_version == latest_version
        fail_msg: >-
          Installed version is "{{ installed_version }}",
          but must be "{{ latest_version }}".
