- name: Verify
  hosts: all

  tasks:
    - name: Get installed version
      ansible.builtin.shell:
        cmd: |
          set -euo pipefail
          export PATH=/usr/local/bin:$PATH
          if command -v sam &> /dev/null; then
            sam --version | sed -n -E 's/.*version (.+)/\1/p'
          fi
        executable: /usr/bin/bash
      register: get_installed_version
      changed_when: false

    - name: Set installed version
      ansible.builtin.set_fact:
        installed_version: >-
          {{ get_installed_version.stdout | regex_search(".+\..+\..+") }}

    - name: Get latest version
      ansible.builtin.shell:
        cmd: |
          set -euo pipefail
          curl --silent --fail-with-body {{ github }} \
            | sed -n -E 's/.*"tag_name": "(.+)",.*/\1/p' \
            | cut -c2-
        executable: /usr/bin/bash
      vars:
        github: https://api.github.com/repos/aws/aws-sam-cli/releases/latest
      register: get_latest_version
      changed_when: false

    - name: Set latest version
      ansible.builtin.set_fact:
        latest_version: >-
          {{ get_latest_version.stdout | regex_search(".+\..+\..+") }}

    - name: Verify installed version correct
      ansible.builtin.assert:
        that:
          - installed_version == latest_version
        fail_msg: >-
          Installed version is "{{ installed_version }}", but must be "{{ latest_version }}".
